import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";
import Header1 from "./components/header2";
import { CartProvider } from "./context";
import { Toaster } from "react-hot-toast"; // Import Toaster for notifications

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Add a link to the fonts in the public folder if necessary */}
        {/* <link rel="stylesheet" href="/fonts/GeistVF.woff" /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      > <ClerkProvider>
        <CartProvider>
          <Header1 />
          <Toaster /> {/* Toaster component for global notifications */}
          <main>{children}</main>
          <Footer />
        </CartProvider></ClerkProvider>
      </body>
    </html>
  );
}
